version: 2

sources:
  - name: jaffle_shop           # logical name for the dataset (source)
    database: dbt-tutorial      # BigQuery project
    schema: jaffle_shop         # BigQuery dataset
    tables:
      - name: customers # logical name for the table (source)
        identifier: customers # BigQuery table
        columns:
          - name: id
            data_tests:
            - unique
            - not_null

      - name: orders
        # We can skip identifier, as it has the name (orders) in both dbt and DWH.
        columns:
          - name: id
            data_tests:
            - unique
            - not_null
    
  - name: stripe
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
  